version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "employee"
      POSTGRES_USER: "de_sprint"
      POSTGRES_PASSWORD: "de_sprint"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"